(() => {
  'use strict';

  const EB = window.EB = window.EB || {};

  EB.LEVELS = Object.freeze({
    terra_viva: {
      id: "terra_viva",
      name: "TERRA VIVA",
      subtitle: "Antes das velas",
      palette: "village",
      theme: "village",
      width: 8600,
      height: 900,
      spawn: {
        x: 380,
        y: 640,
      },
      cameraStart: {
        x: 0,
        y: 0,
      },
      nextLevel: "aldeia_chamas",
      introCinematic: "opening",
      platforms: [
        {
          x: 0,
          y: 760,
          w: 1800,
          h: 140,
          material: "earth",
          oneWay: false,
        },
        {
          x: 1800,
          y: 740,
          w: 950,
          h: 160,
          material: "earth",
          oneWay: false,
        },
        {
          x: 2750,
          y: 780,
          w: 1650,
          h: 120,
          material: "earth",
          oneWay: false,
        },
        {
          x: 4400,
          y: 720,
          w: 1300,
          h: 180,
          material: "earth",
          oneWay: false,
        },
        {
          x: 5700,
          y: 760,
          w: 1500,
          h: 140,
          material: "earth",
          oneWay: false,
        },
        {
          x: 7200,
          y: 700,
          w: 1400,
          h: 200,
          material: "earth",
          oneWay: false,
        },
        {
          x: 620,
          y: 620,
          w: 360,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 1120,
          y: 560,
          w: 420,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 2100,
          y: 610,
          w: 360,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 3050,
          y: 630,
          w: 420,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 3820,
          y: 530,
          w: 350,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 4680,
          y: 570,
          w: 480,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 6020,
          y: 600,
          w: 380,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 6660,
          y: 510,
          w: 420,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 7580,
          y: 560,
          w: 460,
          h: 35,
          material: "stone",
          oneWay: true,
        },
      ],
      decor: [
        {
          type: "tree",
          x: 200,
          y: 760,
          scale: 0.9443,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 620,
          y: 760,
          scale: 0.9869,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 1040,
          y: 760,
          scale: 0.7935,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 1460,
          y: 760,
          scale: 0.8065,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 1880,
          y: 760,
          scale: 0.7848,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 2300,
          y: 760,
          scale: 0.8788,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 2720,
          y: 760,
          scale: 1.0102,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 3140,
          y: 760,
          scale: 0.8944,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 3560,
          y: 760,
          scale: 1.0047,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 3980,
          y: 760,
          scale: 0.8243,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 4400,
          y: 760,
          scale: 1.1284,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 4820,
          y: 760,
          scale: 1.3186,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 5240,
          y: 760,
          scale: 1.1013,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 5660,
          y: 760,
          scale: 1.3358,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 6080,
          y: 760,
          scale: 1.084,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 6500,
          y: 760,
          scale: 0.9238,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 6920,
          y: 760,
          scale: 1.0744,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 7340,
          y: 760,
          scale: 0.9351,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 7760,
          y: 760,
          scale: 0.8118,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 8180,
          y: 760,
          scale: 1.1333,
          variant: 2,
          layer: "mid",
        },
        {
          type: "bush",
          x: 460,
          y: 760,
          scale: 0.7682,
          variant: 0,
          layer: "front",
        },
        {
          type: "bush",
          x: 980,
          y: 760,
          scale: 1.0951,
          variant: 1,
          layer: "front",
        },
        {
          type: "bush",
          x: 1550,
          y: 760,
          scale: 1.0475,
          variant: 3,
          layer: "front",
        },
        {
          type: "bush",
          x: 2340,
          y: 760,
          scale: 1.2441,
          variant: 3,
          layer: "front",
        },
        {
          type: "bush",
          x: 2920,
          y: 760,
          scale: 1.1099,
          variant: 3,
          layer: "front",
        },
        {
          type: "bush",
          x: 3640,
          y: 760,
          scale: 0.9531,
          variant: 1,
          layer: "front",
        },
        {
          type: "bush",
          x: 4520,
          y: 760,
          scale: 1.2561,
          variant: 1,
          layer: "front",
        },
        {
          type: "bush",
          x: 5160,
          y: 760,
          scale: 0.7573,
          variant: 2,
          layer: "front",
        },
        {
          type: "bush",
          x: 5940,
          y: 760,
          scale: 1.0676,
          variant: 2,
          layer: "front",
        },
        {
          type: "bush",
          x: 6880,
          y: 760,
          scale: 1.2106,
          variant: 2,
          layer: "front",
        },
        {
          type: "bush",
          x: 7700,
          y: 760,
          scale: 1.1263,
          variant: 0,
          layer: "front",
        },
        {
          type: "bush",
          x: 8240,
          y: 760,
          scale: 0.7826,
          variant: 3,
          layer: "front",
        },
        {
          type: "hut",
          x: 220,
          y: 760,
          scale: 0.8995,
          variant: 1,
          layer: "back",
        },
        {
          type: "hut",
          x: 1350,
          y: 760,
          scale: 0.8956,
          variant: 1,
          layer: "back",
        },
        {
          type: "hut",
          x: 2500,
          y: 760,
          scale: 0.9765,
          variant: 2,
          layer: "back",
        },
        {
          type: "hut",
          x: 4200,
          y: 760,
          scale: 0.8733,
          variant: 2,
          layer: "back",
        },
        {
          type: "hut",
          x: 5300,
          y: 760,
          scale: 1.0219,
          variant: 1,
          layer: "back",
        },
        {
          type: "river",
          x: 3250,
          y: 760,
          scale: 1,
          variant: 0,
          width: 880,
        },
        {
          type: "canoe",
          x: 3470,
          y: 746,
          scale: 0.9,
          variant: 0,
        },
        {
          type: "firepit",
          x: 1420,
          y: 742,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "banner",
          x: 930,
          y: 750,
          scale: 1,
          variant: 0,
        },
        {
          type: "banner",
          x: 5150,
          y: 750,
          scale: 1,
          variant: 1,
        },
        {
          type: "waterfall",
          x: 7980,
          y: 420,
          scale: 1.15,
          variant: 0,
          layer: "back",
        },
        {
          type: "lookout",
          x: 8180,
          y: 700,
          scale: 1,
          variant: 0,
        },
      ],
      npcs: [
        {
          id: "potira",
          name: "Potira",
          x: 1320,
          y: 680,
          dialogue: "potiraOpening",
          kind: "potira",
          interact: true,
        },
        {
          id: "elder",
          name: "Cunhambebe",
          x: 2520,
          y: 660,
          dialogue: "elderOpening",
          kind: "elder",
          interact: true,
        },
        {
          id: "child_1",
          name: "Arani",
          x: 730,
          y: 690,
          dialogue: "ambientChild",
          kind: "child",
          interact: true,
        },
        {
          id: "fisher_1",
          name: "Pescador",
          x: 3340,
          y: 680,
          dialogue: "ambientFisher",
          kind: "villager",
          interact: true,
        },
        {
          id: "craftswoman",
          name: "Artesã",
          x: 4970,
          y: 680,
          dialogue: "ambientCraft",
          kind: "villager",
          interact: true,
        },
      ],
      items: [
        {
          id: "herb_1",
          type: "herb",
          x: 2980,
          y: 585,
          amount: 1,
        },
        {
          id: "herb_2",
          type: "herb",
          x: 3950,
          y: 485,
          amount: 1,
        },
        {
          id: "herb_3",
          type: "herb",
          x: 6720,
          y: 465,
          amount: 1,
        },
        {
          id: "memory_1",
          type: "memory",
          x: 8120,
          y: 505,
          amount: 1,
        },
        {
          id: "arrow_bundle",
          type: "arrows",
          x: 5580,
          y: 675,
          amount: 4,
        },
      ],
      targets: [
        {
          id: "training_1",
          x: 2050,
          y: 650,
          hitsRequired: 3,
        },
        {
          id: "training_2",
          x: 2240,
          y: 650,
          hitsRequired: 2,
        },
      ],
      triggers: [
        {
          id: "mirante",
          x: 8080,
          y: 360,
          w: 420,
          h: 420,
          action: {
            type: "setFlag",
            key: "reached_mirante",
          },
          once: true,
        },
      ],
      objectives: [
        {
          id: "talk_potira",
          text: "Fale com Potira perto da casa principal.",
          condition: {
            type: "flag",
            key: "talked_potira",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "training",
          text: "Acerte os alvos de treino 5 vezes.",
          condition: {
            type: "counter",
            key: "targetHits",
            value: 5,
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "herbs",
          text: "Recolha 3 ervas medicinais para a aldeia.",
          condition: {
            type: "counter",
            key: "herbs",
            value: 3,
          },
          onComplete: [
            {
              type: "dialogue",
              id: "potiraAfterTraining",
            },
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "elder",
          text: "Converse com Cunhambebe sobre as velas vistas ao sul.",
          condition: {
            type: "flag",
            key: "talked_elder",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "mirante",
          text: "Alcance o mirante e observe o horizonte.",
          condition: {
            type: "flag",
            key: "reached_mirante",
          },
          onComplete: [
            {
              type: "cinematic",
              id: "invasion",
            },
            {
              type: "completeLevel",
            },
          ],
        },
      ],
      checkpoints: [
        {
          id: "cp_village",
          x: 1200,
          y: 650,
        },
        {
          id: "cp_river",
          x: 4500,
          y: 640,
        },
        {
          id: "cp_mirante",
          x: 7420,
          y: 590,
        },
      ],
      codexUnlocks: [
        "land-before-colony",
        "tupi-coast",
        "aimbere",
        "body-paint",
      ],
      ambient: {
        birds: 38,
        fireflies: 22,
        leaves: 46,
        rain: 0,
        embers: 0,
        mist: 0.16,
        water: 0.55,
      },
    },
    aldeia_chamas: {
      id: "aldeia_chamas",
      name: "ALDEIA EM CHAMAS",
      subtitle: "A terra ferida",
      palette: "fire",
      theme: "danger",
      width: 9000,
      height: 900,
      spawn: {
        x: 260,
        y: 650,
      },
      nextLevel: "aguas_resistencia",
      introDialogue: "invasionStart",
      platforms: [
        {
          x: 0,
          y: 770,
          w: 1200,
          h: 130,
          material: "earth",
          oneWay: false,
        },
        {
          x: 1200,
          y: 735,
          w: 840,
          h: 165,
          material: "earth",
          oneWay: false,
        },
        {
          x: 2040,
          y: 790,
          w: 970,
          h: 110,
          material: "earth",
          oneWay: false,
        },
        {
          x: 3010,
          y: 720,
          w: 1250,
          h: 180,
          material: "earth",
          oneWay: false,
        },
        {
          x: 4260,
          y: 770,
          w: 1050,
          h: 130,
          material: "earth",
          oneWay: false,
        },
        {
          x: 5310,
          y: 700,
          w: 1320,
          h: 200,
          material: "earth",
          oneWay: false,
        },
        {
          x: 6630,
          y: 755,
          w: 960,
          h: 145,
          material: "earth",
          oneWay: false,
        },
        {
          x: 7590,
          y: 690,
          w: 1410,
          h: 210,
          material: "earth",
          oneWay: false,
        },
        {
          x: 560,
          y: 590,
          w: 350,
          h: 35,
          material: "burnedWood",
          oneWay: true,
        },
        {
          x: 1420,
          y: 560,
          w: 420,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 2310,
          y: 620,
          w: 380,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 3360,
          y: 540,
          w: 440,
          h: 35,
          material: "burnedWood",
          oneWay: true,
        },
        {
          x: 4540,
          y: 590,
          w: 370,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 5480,
          y: 500,
          w: 460,
          h: 35,
          material: "burnedWood",
          oneWay: true,
        },
        {
          x: 6240,
          y: 570,
          w: 380,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 7050,
          y: 510,
          w: 460,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 8080,
          y: 460,
          w: 510,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
      ],
      decor: [
        {
          type: "burnedTree",
          x: 100,
          y: 760,
          scale: 0.9711,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 450,
          y: 760,
          scale: 1.1363,
          variant: 4,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 800,
          y: 760,
          scale: 1.268,
          variant: 0,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 1150,
          y: 760,
          scale: 1.296,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 1500,
          y: 760,
          scale: 1.0582,
          variant: 0,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 1850,
          y: 760,
          scale: 0.7894,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 2200,
          y: 760,
          scale: 1.1706,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 2550,
          y: 760,
          scale: 0.935,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 2900,
          y: 760,
          scale: 1.3266,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 3250,
          y: 760,
          scale: 0.7647,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 3600,
          y: 760,
          scale: 0.9811,
          variant: 4,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 3950,
          y: 760,
          scale: 0.8261,
          variant: 0,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 4300,
          y: 760,
          scale: 0.8918,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 4650,
          y: 760,
          scale: 0.8341,
          variant: 1,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 5000,
          y: 760,
          scale: 1.0086,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 5350,
          y: 760,
          scale: 0.8024,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 5700,
          y: 760,
          scale: 1.0111,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 6050,
          y: 760,
          scale: 1.3242,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 6400,
          y: 760,
          scale: 1.3116,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 6750,
          y: 760,
          scale: 1.2092,
          variant: 2,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 7100,
          y: 760,
          scale: 1.1938,
          variant: 3,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 7450,
          y: 760,
          scale: 1.3725,
          variant: 1,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 7800,
          y: 760,
          scale: 0.8039,
          variant: 1,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 8150,
          y: 760,
          scale: 0.9008,
          variant: 1,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 8500,
          y: 760,
          scale: 0.7578,
          variant: 4,
          layer: "mid",
        },
        {
          type: "burnedTree",
          x: 8850,
          y: 760,
          scale: 0.8685,
          variant: 2,
          layer: "mid",
        },
        {
          type: "fire",
          x: 380,
          y: 750,
          scale: 0.8018,
          variant: 1,
          light: true,
        },
        {
          type: "fire",
          x: 980,
          y: 750,
          scale: 1.0406,
          variant: 2,
          light: true,
        },
        {
          type: "fire",
          x: 1660,
          y: 750,
          scale: 1.0549,
          variant: 0,
          light: true,
        },
        {
          type: "fire",
          x: 2480,
          y: 750,
          scale: 1.1107,
          variant: 2,
          light: true,
        },
        {
          type: "fire",
          x: 3290,
          y: 750,
          scale: 1.2276,
          variant: 2,
          light: true,
        },
        {
          type: "fire",
          x: 4050,
          y: 750,
          scale: 1.1043,
          variant: 0,
          light: true,
        },
        {
          type: "fire",
          x: 4820,
          y: 750,
          scale: 1.0055,
          variant: 2,
          light: true,
        },
        {
          type: "fire",
          x: 5750,
          y: 750,
          scale: 1.159,
          variant: 1,
          light: true,
        },
        {
          type: "fire",
          x: 6470,
          y: 750,
          scale: 0.9791,
          variant: 1,
          light: true,
        },
        {
          type: "fire",
          x: 7240,
          y: 750,
          scale: 0.8466,
          variant: 2,
          light: true,
        },
        {
          type: "fire",
          x: 8360,
          y: 750,
          scale: 0.9802,
          variant: 0,
          light: true,
        },
        {
          type: "burnedHut",
          x: 560,
          y: 760,
          scale: 0.8702,
          variant: 0,
          layer: "back",
        },
        {
          type: "burnedHut",
          x: 1460,
          y: 760,
          scale: 0.9822,
          variant: 0,
          layer: "back",
        },
        {
          type: "burnedHut",
          x: 3000,
          y: 760,
          scale: 0.952,
          variant: 0,
          layer: "back",
        },
        {
          type: "burnedHut",
          x: 4480,
          y: 760,
          scale: 0.8807,
          variant: 2,
          layer: "back",
        },
        {
          type: "burnedHut",
          x: 5930,
          y: 760,
          scale: 0.8954,
          variant: 0,
          layer: "back",
        },
        {
          type: "smokeColumn",
          x: 1180,
          y: 760,
          scale: 1.4,
          variant: 0,
          layer: "back",
        },
        {
          type: "smokeColumn",
          x: 3920,
          y: 760,
          scale: 1.6,
          variant: 1,
          layer: "back",
        },
        {
          type: "smokeColumn",
          x: 6810,
          y: 760,
          scale: 1.5,
          variant: 2,
          layer: "back",
        },
        {
          type: "shore",
          x: 7900,
          y: 690,
          scale: 1,
          variant: 0,
          width: 1100,
        },
        {
          type: "landingBoat",
          x: 8380,
          y: 710,
          scale: 1.1,
          variant: 0,
          layer: "back",
        },
      ],
      enemies: [
        {
          id: "s01",
          type: "sailor",
          x: 980,
          y: 680,
          patrol: 190,
          group: "wave_a",
        },
        {
          id: "s02",
          type: "sailor",
          x: 1650,
          y: 650,
          patrol: 230,
          group: "wave_a",
        },
        {
          id: "a01",
          type: "arquebusier",
          x: 1780,
          y: 500,
          patrol: 120,
          group: "wave_a",
        },
        {
          id: "s03",
          type: "shield",
          x: 2480,
          y: 700,
          patrol: 180,
          group: "wave_b",
        },
        {
          id: "h01",
          type: "hound",
          x: 2860,
          y: 715,
          patrol: 260,
          group: "wave_b",
        },
        {
          id: "s04",
          type: "sailor",
          x: 3540,
          y: 640,
          patrol: 260,
          group: "wave_b",
        },
        {
          id: "a02",
          type: "arquebusier",
          x: 3760,
          y: 480,
          patrol: 150,
          group: "wave_b",
        },
        {
          id: "s05",
          type: "sailor",
          x: 4680,
          y: 680,
          patrol: 180,
          group: "wave_c",
        },
        {
          id: "s06",
          type: "shield",
          x: 5050,
          y: 680,
          patrol: 160,
          group: "wave_c",
        },
        {
          id: "h02",
          type: "hound",
          x: 5700,
          y: 635,
          patrol: 250,
          group: "wave_c",
        },
        {
          id: "a03",
          type: "arquebusier",
          x: 5820,
          y: 440,
          patrol: 140,
          group: "wave_c",
        },
        {
          id: "o01",
          type: "officer",
          x: 6460,
          y: 670,
          patrol: 200,
          group: "wave_d",
        },
        {
          id: "s07",
          type: "sailor",
          x: 6980,
          y: 680,
          patrol: 200,
          group: "wave_d",
        },
        {
          id: "a04",
          type: "arquebusier",
          x: 7200,
          y: 450,
          patrol: 120,
          group: "wave_d",
        },
        {
          id: "e01",
          type: "elite",
          x: 7770,
          y: 620,
          patrol: 180,
          group: "wave_e",
          elite: true,
        },
      ],
      npcs: [
        {
          id: "survivor_intro",
          name: "Sobrevivente",
          x: 380,
          y: 690,
          dialogue: "invasionStart",
          kind: "injured",
          interact: true,
        },
      ],
      cages: [
        {
          id: "cage_1",
          x: 1910,
          y: 650,
          dialogue: "rescuedOne",
        },
        {
          id: "cage_2",
          x: 4780,
          y: 680,
          dialogue: "rescuedTwo",
        },
        {
          id: "cage_3",
          x: 7040,
          y: 680,
          dialogue: "rescuedThree",
        },
      ],
      items: [
        {
          id: "herb_f1",
          type: "herb",
          x: 1520,
          y: 510,
          amount: 1,
        },
        {
          id: "herb_f2",
          type: "herb",
          x: 4370,
          y: 720,
          amount: 1,
        },
        {
          id: "arrows_f1",
          type: "arrows",
          x: 2700,
          y: 575,
          amount: 4,
        },
        {
          id: "arrows_f2",
          type: "arrows",
          x: 6120,
          y: 525,
          amount: 5,
        },
        {
          id: "memory_f1",
          type: "memory",
          x: 8460,
          y: 405,
          amount: 1,
        },
      ],
      triggers: [
        {
          id: "boss_arena_fire",
          x: 8040,
          y: 360,
          w: 820,
          h: 480,
          action: {
            type: "startBoss",
            boss: "landingCaptain",
            id: "boss_landing",
          },
          once: true,
        },
      ],
      gates: [
        {
          id: "gate_boss_fire",
          x: 8840,
          y: 400,
          w: 50,
          h: 360,
          openFlag: "boss_landing_dead",
          initiallyOpen: false,
        },
      ],
      objectives: [
        {
          id: "rescue",
          text: "Liberte 3 prisioneiros antes que sejam levados à praia.",
          condition: {
            type: "counter",
            key: "rescued",
            value: 3,
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "reach_shore",
          text: "Atravesse a aldeia e alcance a praia.",
          condition: {
            type: "flag",
            key: "boss_landing_started",
          },
          onComplete: [
            {
              type: "dialogue",
              id: "landingBossIntro",
            },
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "boss",
          text: "Derrote o Capitão do Desembarque.",
          condition: {
            type: "flag",
            key: "boss_landing_dead",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "escape",
          text: "Use a canoa para seguir os navios pelo mangue.",
          condition: {
            type: "reach",
            x: 8730,
            y: 570,
            w: 220,
            h: 250,
          },
          onComplete: [
            {
              type: "cinematic",
              id: "waters",
            },
            {
              type: "completeLevel",
            },
          ],
        },
      ],
      checkpoints: [
        {
          id: "cp_fire_1",
          x: 1180,
          y: 650,
        },
        {
          id: "cp_fire_2",
          x: 4200,
          y: 650,
        },
        {
          id: "cp_fire_3",
          x: 6700,
          y: 640,
        },
      ],
      codexUnlocks: [
        "enslavement",
        "firearms",
        "forest-knowledge",
      ],
      ambient: {
        birds: 5,
        fireflies: 0,
        leaves: 18,
        rain: 0,
        embers: 130,
        mist: 0.3,
        water: 0.12,
      },
    },
    aguas_resistencia: {
      id: "aguas_resistencia",
      name: "ÁGUAS DA RESISTÊNCIA",
      subtitle: "O rio como caminho",
      palette: "water",
      theme: "water",
      width: 9300,
      height: 900,
      spawn: {
        x: 220,
        y: 620,
      },
      nextLevel: "fogos_alianca",
      introDialogue: "watersEntry",
      platforms: [
        {
          x: 0,
          y: 720,
          w: 950,
          h: 180,
          material: "mangrove",
          oneWay: false,
        },
        {
          x: 950,
          y: 780,
          w: 980,
          h: 120,
          material: "mud",
          oneWay: false,
        },
        {
          x: 1930,
          y: 700,
          w: 820,
          h: 200,
          material: "mangrove",
          oneWay: false,
        },
        {
          x: 2750,
          y: 790,
          w: 1250,
          h: 110,
          material: "mud",
          oneWay: false,
        },
        {
          x: 4000,
          y: 680,
          w: 1040,
          h: 220,
          material: "mangrove",
          oneWay: false,
        },
        {
          x: 5040,
          y: 760,
          w: 1150,
          h: 140,
          material: "mud",
          oneWay: false,
        },
        {
          x: 6190,
          y: 690,
          w: 900,
          h: 210,
          material: "mangrove",
          oneWay: false,
        },
        {
          x: 7090,
          y: 770,
          w: 1110,
          h: 130,
          material: "mud",
          oneWay: false,
        },
        {
          x: 8200,
          y: 650,
          w: 1100,
          h: 250,
          material: "shore",
          oneWay: false,
        },
        {
          x: 640,
          y: 520,
          w: 320,
          h: 34,
          material: "root",
          oneWay: true,
        },
        {
          x: 1390,
          y: 590,
          w: 370,
          h: 34,
          material: "canoe",
          oneWay: true,
        },
        {
          x: 2250,
          y: 500,
          w: 430,
          h: 34,
          material: "root",
          oneWay: true,
        },
        {
          x: 3180,
          y: 610,
          w: 350,
          h: 34,
          material: "wreck",
          oneWay: true,
        },
        {
          x: 4180,
          y: 480,
          w: 480,
          h: 34,
          material: "root",
          oneWay: true,
        },
        {
          x: 5340,
          y: 570,
          w: 420,
          h: 34,
          material: "canoe",
          oneWay: true,
        },
        {
          x: 6420,
          y: 500,
          w: 430,
          h: 34,
          material: "root",
          oneWay: true,
        },
        {
          x: 7380,
          y: 560,
          w: 390,
          h: 34,
          material: "wreck",
          oneWay: true,
        },
        {
          x: 8450,
          y: 440,
          w: 520,
          h: 34,
          material: "shipWood",
          oneWay: true,
        },
      ],
      decor: [
        {
          type: "mangroveTree",
          x: 100,
          y: 735,
          scale: 1.4168,
          variant: 4,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 420,
          y: 735,
          scale: 0.8166,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 740,
          y: 735,
          scale: 1.1991,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 1060,
          y: 735,
          scale: 1.2124,
          variant: 2,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 1380,
          y: 735,
          scale: 1.1915,
          variant: 3,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 1700,
          y: 735,
          scale: 0.8798,
          variant: 3,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 2020,
          y: 735,
          scale: 1.4455,
          variant: 3,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 2340,
          y: 735,
          scale: 1.1123,
          variant: 2,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 2660,
          y: 735,
          scale: 0.8558,
          variant: 0,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 2980,
          y: 735,
          scale: 1.2873,
          variant: 5,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 3300,
          y: 735,
          scale: 0.9721,
          variant: 5,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 3620,
          y: 735,
          scale: 0.9049,
          variant: 0,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 3940,
          y: 735,
          scale: 0.9334,
          variant: 4,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 4260,
          y: 735,
          scale: 1.0351,
          variant: 5,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 4580,
          y: 735,
          scale: 1.1531,
          variant: 0,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 4900,
          y: 735,
          scale: 1.2928,
          variant: 2,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 5220,
          y: 735,
          scale: 1.436,
          variant: 0,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 5540,
          y: 735,
          scale: 1.2525,
          variant: 2,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 5860,
          y: 735,
          scale: 1.137,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 6180,
          y: 735,
          scale: 1.0312,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 6500,
          y: 735,
          scale: 1.1462,
          variant: 4,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 6820,
          y: 735,
          scale: 1.0143,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 7140,
          y: 735,
          scale: 1.1986,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 7460,
          y: 735,
          scale: 1.324,
          variant: 3,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 7780,
          y: 735,
          scale: 1.2809,
          variant: 1,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 8100,
          y: 735,
          scale: 0.9299,
          variant: 3,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 8420,
          y: 735,
          scale: 1.0311,
          variant: 0,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 8740,
          y: 735,
          scale: 1.4432,
          variant: 2,
          layer: "mid",
        },
        {
          type: "mangroveTree",
          x: 9060,
          y: 735,
          scale: 1.107,
          variant: 1,
          layer: "mid",
        },
        {
          type: "waterPlant",
          x: 420,
          y: 790,
          scale: 1.1155,
          variant: 2,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 1200,
          y: 790,
          scale: 0.9683,
          variant: 2,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 2100,
          y: 790,
          scale: 1.273,
          variant: 2,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 3400,
          y: 790,
          scale: 0.7483,
          variant: 0,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 4550,
          y: 790,
          scale: 0.8361,
          variant: 1,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 5600,
          y: 790,
          scale: 0.9026,
          variant: 3,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 6650,
          y: 790,
          scale: 1.0744,
          variant: 0,
          layer: "front",
        },
        {
          type: "waterPlant",
          x: 7750,
          y: 790,
          scale: 0.9877,
          variant: 2,
          layer: "front",
        },
        {
          type: "waterSurface",
          x: 0,
          y: 430,
          scale: 1,
          variant: 0,
          width: 9300,
          depth: 470,
        },
        {
          type: "sunRays",
          x: 2300,
          y: 0,
          scale: 1,
          variant: 0,
          layer: "back",
        },
        {
          type: "wreck",
          x: 3320,
          y: 620,
          scale: 1.1,
          variant: 0,
        },
        {
          type: "wreck",
          x: 7540,
          y: 565,
          scale: 0.9,
          variant: 1,
        },
        {
          type: "patrolShip",
          x: 8710,
          y: 625,
          scale: 1.25,
          variant: 0,
          layer: "back",
        },
      ],
      enemies: [
        {
          id: "c01",
          type: "canoe",
          x: 1450,
          y: 500,
          patrol: 300,
          group: "water_a",
        },
        {
          id: "c02",
          type: "canoe",
          x: 2600,
          y: 510,
          patrol: 280,
          group: "water_a",
        },
        {
          id: "a_w1",
          type: "arquebusier",
          x: 2380,
          y: 440,
          patrol: 130,
          group: "water_a",
        },
        {
          id: "c03",
          type: "canoe",
          x: 3730,
          y: 520,
          patrol: 340,
          group: "water_b",
        },
        {
          id: "h_w1",
          type: "hound",
          x: 4210,
          y: 610,
          patrol: 180,
          group: "water_b",
        },
        {
          id: "a_w2",
          type: "arquebusier",
          x: 4480,
          y: 420,
          patrol: 140,
          group: "water_b",
        },
        {
          id: "c04",
          type: "canoe",
          x: 5530,
          y: 500,
          patrol: 320,
          group: "water_c",
        },
        {
          id: "s_w1",
          type: "sailor",
          x: 6260,
          y: 610,
          patrol: 180,
          group: "water_c",
        },
        {
          id: "a_w3",
          type: "arquebusier",
          x: 6600,
          y: 440,
          patrol: 130,
          group: "water_c",
        },
        {
          id: "c05",
          type: "canoe",
          x: 7520,
          y: 510,
          patrol: 300,
          group: "water_d",
        },
        {
          id: "e_w1",
          type: "elite",
          x: 8250,
          y: 560,
          patrol: 170,
          group: "water_d",
          elite: true,
        },
      ],
      waterZones: [
        {
          id: "main_water",
          x: 0,
          y: 430,
          w: 9300,
          h: 470,
          currentX: 16,
          currentY: 0,
        },
      ],
      npcs: [
        {
          id: "rower",
          name: "Remador ferido",
          x: 3920,
          y: 615,
          dialogue: "waterRescue",
          kind: "injured",
          interact: true,
        },
      ],
      cages: [
        {
          id: "water_cage_1",
          x: 3110,
          y: 615,
          dialogue: "waterRescue",
          underwater: false,
        },
        {
          id: "water_cage_2",
          x: 5890,
          y: 635,
          dialogue: "waterRescue",
          underwater: false,
        },
      ],
      items: [
        {
          id: "air_1",
          type: "airBubble",
          x: 1880,
          y: 640,
          amount: 1,
        },
        {
          id: "air_2",
          type: "airBubble",
          x: 4700,
          y: 680,
          amount: 1,
        },
        {
          id: "air_3",
          type: "airBubble",
          x: 6940,
          y: 630,
          amount: 1,
        },
        {
          id: "arrows_w1",
          type: "arrows",
          x: 4100,
          y: 430,
          amount: 5,
        },
        {
          id: "herb_w1",
          type: "herb",
          x: 7210,
          y: 520,
          amount: 1,
        },
        {
          id: "memory_w1",
          type: "memory",
          x: 8810,
          y: 390,
          amount: 1,
        },
      ],
      triggers: [
        {
          id: "boss_water",
          x: 8360,
          y: 300,
          w: 800,
          h: 520,
          action: {
            type: "startBoss",
            boss: "patrolShip",
            id: "boss_patrol",
          },
          once: true,
        },
      ],
      objectives: [
        {
          id: "free_water",
          text: "Liberte os 2 remadores capturados no mangue.",
          condition: {
            type: "counter",
            key: "rescued",
            value: 2,
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "reach_ship",
          text: "Atravesse as águas sem perder o fôlego.",
          condition: {
            type: "flag",
            key: "boss_patrol_started",
          },
          onComplete: [
            {
              type: "dialogue",
              id: "shipBossIntro",
            },
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "sink_ship",
          text: "Destrua o bergantim que bloqueia a baía.",
          condition: {
            type: "flag",
            key: "boss_patrol_dead",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "leave_mangrove",
          text: "Alcance a passagem aberta para as canoas aliadas.",
          condition: {
            type: "reach",
            x: 9040,
            y: 400,
            w: 220,
            h: 360,
          },
          onComplete: [
            {
              type: "cinematic",
              id: "confederation",
            },
            {
              type: "completeLevel",
            },
          ],
        },
      ],
      checkpoints: [
        {
          id: "cp_water_1",
          x: 1200,
          y: 520,
        },
        {
          id: "cp_water_2",
          x: 4180,
          y: 420,
        },
        {
          id: "cp_water_3",
          x: 7150,
          y: 500,
        },
      ],
      codexUnlocks: [
        "canoes",
        "guanabara",
        "alliances",
      ],
      ambient: {
        birds: 28,
        fireflies: 0,
        leaves: 20,
        rain: 0.08,
        embers: 0,
        mist: 0.34,
        water: 1,
      },
    },
    fogos_alianca: {
      id: "fogos_alianca",
      name: "FOGOS DA ALIANÇA",
      subtitle: "Muitos povos, muitos caminhos",
      palette: "storm",
      theme: "council",
      width: 9200,
      height: 900,
      spawn: {
        x: 260,
        y: 650,
      },
      nextLevel: "urucumirim",
      introDialogue: "councilOpening",
      platforms: [
        {
          x: 0,
          y: 760,
          w: 1250,
          h: 140,
          material: "earth",
          oneWay: false,
        },
        {
          x: 1250,
          y: 700,
          w: 1150,
          h: 200,
          material: "earth",
          oneWay: false,
        },
        {
          x: 2400,
          y: 780,
          w: 980,
          h: 120,
          material: "earth",
          oneWay: false,
        },
        {
          x: 3380,
          y: 690,
          w: 1220,
          h: 210,
          material: "earth",
          oneWay: false,
        },
        {
          x: 4600,
          y: 750,
          w: 1080,
          h: 150,
          material: "earth",
          oneWay: false,
        },
        {
          x: 5680,
          y: 680,
          w: 1200,
          h: 220,
          material: "earth",
          oneWay: false,
        },
        {
          x: 6880,
          y: 760,
          w: 1120,
          h: 140,
          material: "earth",
          oneWay: false,
        },
        {
          x: 8000,
          y: 650,
          w: 1200,
          h: 250,
          material: "earth",
          oneWay: false,
        },
        {
          x: 550,
          y: 580,
          w: 420,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 1520,
          y: 520,
          w: 460,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 2650,
          y: 600,
          w: 360,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 3600,
          y: 500,
          w: 470,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 4800,
          y: 570,
          w: 420,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 5880,
          y: 470,
          w: 520,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 7100,
          y: 560,
          w: 430,
          h: 35,
          material: "root",
          oneWay: true,
        },
        {
          x: 8200,
          y: 430,
          w: 560,
          h: 35,
          material: "stone",
          oneWay: true,
        },
      ],
      decor: [
        {
          type: "tree",
          x: 100,
          y: 750,
          scale: 1.3198,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 480,
          y: 750,
          scale: 1.3425,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 860,
          y: 750,
          scale: 1.3914,
          variant: 5,
          layer: "mid",
        },
        {
          type: "tree",
          x: 1240,
          y: 750,
          scale: 1.2876,
          variant: 3,
          layer: "mid",
        },
        {
          type: "tree",
          x: 1620,
          y: 750,
          scale: 1.3779,
          variant: 3,
          layer: "mid",
        },
        {
          type: "tree",
          x: 2000,
          y: 750,
          scale: 1.3129,
          variant: 2,
          layer: "mid",
        },
        {
          type: "tree",
          x: 2380,
          y: 750,
          scale: 0.8564,
          variant: 5,
          layer: "mid",
        },
        {
          type: "tree",
          x: 2760,
          y: 750,
          scale: 1.0573,
          variant: 3,
          layer: "mid",
        },
        {
          type: "tree",
          x: 3140,
          y: 750,
          scale: 1.2832,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 3520,
          y: 750,
          scale: 1.2711,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 3900,
          y: 750,
          scale: 1.4455,
          variant: 0,
          layer: "mid",
        },
        {
          type: "tree",
          x: 4280,
          y: 750,
          scale: 0.8982,
          variant: 3,
          layer: "mid",
        },
        {
          type: "tree",
          x: 4660,
          y: 750,
          scale: 1.3242,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 5040,
          y: 750,
          scale: 1.1975,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 5420,
          y: 750,
          scale: 1.4372,
          variant: 5,
          layer: "mid",
        },
        {
          type: "tree",
          x: 5800,
          y: 750,
          scale: 1.4094,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 6180,
          y: 750,
          scale: 1.1566,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 6560,
          y: 750,
          scale: 0.8139,
          variant: 5,
          layer: "mid",
        },
        {
          type: "tree",
          x: 6940,
          y: 750,
          scale: 1.2223,
          variant: 4,
          layer: "mid",
        },
        {
          type: "tree",
          x: 7320,
          y: 750,
          scale: 1.2872,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 7700,
          y: 750,
          scale: 1.082,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 8080,
          y: 750,
          scale: 1.337,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 8460,
          y: 750,
          scale: 0.8182,
          variant: 1,
          layer: "mid",
        },
        {
          type: "tree",
          x: 8840,
          y: 750,
          scale: 0.9904,
          variant: 1,
          layer: "mid",
        },
        {
          type: "signalBrazier",
          x: 920,
          y: 730,
          scale: 1,
          variant: 2,
          light: false,
        },
        {
          type: "signalBrazier",
          x: 2400,
          y: 730,
          scale: 1,
          variant: 1,
          light: false,
        },
        {
          type: "signalBrazier",
          x: 3820,
          y: 730,
          scale: 1,
          variant: 1,
          light: false,
        },
        {
          type: "signalBrazier",
          x: 5220,
          y: 730,
          scale: 1,
          variant: 2,
          light: false,
        },
        {
          type: "signalBrazier",
          x: 6750,
          y: 730,
          scale: 1,
          variant: 1,
          light: false,
        },
        {
          type: "signalBrazier",
          x: 8360,
          y: 730,
          scale: 1,
          variant: 0,
          light: false,
        },
        {
          type: "warCamp",
          x: 700,
          y: 745,
          scale: 0.8683,
          variant: 2,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 1900,
          y: 745,
          scale: 0.9561,
          variant: 1,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 3100,
          y: 745,
          scale: 1.0487,
          variant: 2,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 4350,
          y: 745,
          scale: 0.9762,
          variant: 2,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 5550,
          y: 745,
          scale: 0.8892,
          variant: 0,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 6600,
          y: 745,
          scale: 1.0071,
          variant: 0,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 7800,
          y: 745,
          scale: 1.1118,
          variant: 0,
          layer: "back",
        },
        {
          type: "warCamp",
          x: 8900,
          y: 745,
          scale: 1.0326,
          variant: 0,
          layer: "back",
        },
        {
          type: "councilFire",
          x: 420,
          y: 740,
          scale: 1.2,
          variant: 0,
          light: true,
        },
        {
          type: "signalTower",
          x: 3650,
          y: 690,
          scale: 1.1,
          variant: 0,
        },
        {
          type: "signalTower",
          x: 5950,
          y: 680,
          scale: 1.1,
          variant: 1,
        },
        {
          type: "signalTower",
          x: 8370,
          y: 650,
          scale: 1.1,
          variant: 2,
        },
      ],
      enemies: [
        {
          id: "sc01",
          type: "sailor",
          x: 2380,
          y: 690,
          patrol: 180,
          group: "scout_a",
        },
        {
          id: "sc02",
          type: "arquebusier",
          x: 2760,
          y: 540,
          patrol: 130,
          group: "scout_a",
        },
        {
          id: "sc03",
          type: "hound",
          x: 3180,
          y: 710,
          patrol: 250,
          group: "scout_a",
        },
        {
          id: "sc04",
          type: "shield",
          x: 4380,
          y: 610,
          patrol: 180,
          group: "scout_b",
        },
        {
          id: "sc05",
          type: "sailor",
          x: 4700,
          y: 670,
          patrol: 220,
          group: "scout_b",
        },
        {
          id: "sc06",
          type: "arquebusier",
          x: 5040,
          y: 510,
          patrol: 130,
          group: "scout_b",
        },
        {
          id: "sc07",
          type: "officer",
          x: 6460,
          y: 600,
          patrol: 190,
          group: "scout_c",
        },
        {
          id: "sc08",
          type: "sailor",
          x: 7040,
          y: 680,
          patrol: 210,
          group: "scout_c",
        },
        {
          id: "sc09",
          type: "arquebusier",
          x: 7240,
          y: 500,
          patrol: 130,
          group: "scout_c",
        },
        {
          id: "sc10",
          type: "elite",
          x: 8560,
          y: 560,
          patrol: 190,
          group: "scout_d",
          elite: true,
        },
      ],
      npcs: [
        {
          id: "cunhambebe",
          name: "Cunhambebe",
          x: 470,
          y: 670,
          dialogue: "councilOpening",
          kind: "elder",
          interact: true,
        },
        {
          id: "messenger_1",
          name: "Mensageiro",
          x: 3520,
          y: 620,
          dialogue: "signalOne",
          kind: "warrior",
          interact: true,
        },
        {
          id: "messenger_2",
          name: "Mensageira",
          x: 5820,
          y: 610,
          dialogue: "signalTwo",
          kind: "warrior",
          interact: true,
        },
        {
          id: "messenger_3",
          name: "Cunhambebe",
          x: 8240,
          y: 580,
          dialogue: "signalThree",
          kind: "elder",
          interact: true,
        },
      ],
      signals: [
        {
          id: "signal_1",
          x: 3780,
          y: 440,
          lit: false,
          dialogue: "signalOne",
        },
        {
          id: "signal_2",
          x: 6120,
          y: 410,
          lit: false,
          dialogue: "signalTwo",
        },
        {
          id: "signal_3",
          x: 8520,
          y: 370,
          lit: false,
          dialogue: "signalThree",
        },
      ],
      items: [
        {
          id: "arrows_c1",
          type: "arrows",
          x: 1990,
          y: 475,
          amount: 4,
        },
        {
          id: "herb_c1",
          type: "herb",
          x: 5310,
          y: 700,
          amount: 1,
        },
        {
          id: "herb_c2",
          type: "herb",
          x: 7440,
          y: 515,
          amount: 1,
        },
        {
          id: "memory_c1",
          type: "memory",
          x: 8820,
          y: 380,
          amount: 1,
        },
      ],
      objectives: [
        {
          id: "signals",
          text: "Acenda os 3 fogos para convocar os aliados.",
          condition: {
            type: "counter",
            key: "signals",
            value: 3,
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "scouts",
          text: "Derrote os batedores que tentam interromper os sinais.",
          condition: {
            type: "counter",
            key: "enemiesDefeated",
            value: 10,
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "march",
          text: "Encontre Cunhambebe no último mirante.",
          condition: {
            type: "flag",
            key: "talked_messenger_3",
          },
          onComplete: [
            {
              type: "cinematic",
              id: "urucumirim",
            },
            {
              type: "completeLevel",
            },
          ],
        },
      ],
      checkpoints: [
        {
          id: "cp_council_1",
          x: 1100,
          y: 610,
        },
        {
          id: "cp_council_2",
          x: 4520,
          y: 600,
        },
        {
          id: "cp_council_3",
          x: 7560,
          y: 610,
        },
      ],
      codexUnlocks: [
        "confederation",
        "oral-memory",
      ],
      ambient: {
        birds: 22,
        fireflies: 18,
        leaves: 58,
        rain: 0.22,
        embers: 6,
        mist: 0.28,
        water: 0.2,
      },
    },
    urucumirim: {
      id: "urucumirim",
      name: "URUÇUMIRIM",
      subtitle: "A fortificação da baía",
      palette: "fortress",
      theme: "fortress",
      width: 9300,
      height: 900,
      spawn: {
        x: 220,
        y: 650,
      },
      nextLevel: "navios_chamas",
      introDialogue: "fortressEntry",
      platforms: [
        {
          x: 0,
          y: 760,
          w: 900,
          h: 140,
          material: "mud",
          oneWay: false,
        },
        {
          x: 900,
          y: 700,
          w: 850,
          h: 200,
          material: "stone",
          oneWay: false,
        },
        {
          x: 1750,
          y: 790,
          w: 950,
          h: 110,
          material: "mud",
          oneWay: false,
        },
        {
          x: 2700,
          y: 680,
          w: 1050,
          h: 220,
          material: "fortress",
          oneWay: false,
        },
        {
          x: 3750,
          y: 760,
          w: 900,
          h: 140,
          material: "stone",
          oneWay: false,
        },
        {
          x: 4650,
          y: 650,
          w: 1280,
          h: 250,
          material: "fortress",
          oneWay: false,
        },
        {
          x: 5930,
          y: 740,
          w: 920,
          h: 160,
          material: "stone",
          oneWay: false,
        },
        {
          x: 6850,
          y: 620,
          w: 1230,
          h: 280,
          material: "fortress",
          oneWay: false,
        },
        {
          x: 8080,
          y: 700,
          w: 1220,
          h: 200,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 450,
          y: 560,
          w: 330,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 1120,
          y: 500,
          w: 400,
          h: 35,
          material: "fortress",
          oneWay: true,
        },
        {
          x: 2040,
          y: 590,
          w: 380,
          h: 35,
          material: "wood",
          oneWay: true,
        },
        {
          x: 2920,
          y: 470,
          w: 450,
          h: 35,
          material: "fortress",
          oneWay: true,
        },
        {
          x: 3980,
          y: 550,
          w: 390,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 4820,
          y: 420,
          w: 520,
          h: 35,
          material: "fortress",
          oneWay: true,
        },
        {
          x: 6120,
          y: 510,
          w: 410,
          h: 35,
          material: "stone",
          oneWay: true,
        },
        {
          x: 7050,
          y: 390,
          w: 530,
          h: 35,
          material: "fortress",
          oneWay: true,
        },
        {
          x: 8250,
          y: 510,
          w: 500,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
      ],
      decor: [
        {
          type: "palisade",
          x: 380,
          y: 740,
          scale: 0.9431,
          variant: 3,
          layer: "back",
        },
        {
          type: "palisade",
          x: 1050,
          y: 740,
          scale: 1.0548,
          variant: 0,
          layer: "back",
        },
        {
          type: "palisade",
          x: 1880,
          y: 740,
          scale: 1.0391,
          variant: 2,
          layer: "back",
        },
        {
          type: "palisade",
          x: 2600,
          y: 740,
          scale: 1.0706,
          variant: 3,
          layer: "back",
        },
        {
          type: "palisade",
          x: 3440,
          y: 740,
          scale: 1.0961,
          variant: 0,
          layer: "back",
        },
        {
          type: "palisade",
          x: 4320,
          y: 740,
          scale: 1.1208,
          variant: 0,
          layer: "back",
        },
        {
          type: "palisade",
          x: 5240,
          y: 740,
          scale: 0.9621,
          variant: 2,
          layer: "back",
        },
        {
          type: "palisade",
          x: 6100,
          y: 740,
          scale: 0.9105,
          variant: 0,
          layer: "back",
        },
        {
          type: "palisade",
          x: 6940,
          y: 740,
          scale: 1.0269,
          variant: 0,
          layer: "back",
        },
        {
          type: "palisade",
          x: 7840,
          y: 740,
          scale: 1.09,
          variant: 0,
          layer: "back",
        },
        {
          type: "palisade",
          x: 8760,
          y: 740,
          scale: 1.0108,
          variant: 1,
          layer: "back",
        },
        {
          type: "watchTower",
          x: 1580,
          y: 700,
          scale: 1.05,
          variant: 2,
          layer: "back",
        },
        {
          type: "watchTower",
          x: 3120,
          y: 700,
          scale: 1.05,
          variant: 1,
          layer: "back",
        },
        {
          type: "watchTower",
          x: 4900,
          y: 700,
          scale: 1.05,
          variant: 1,
          layer: "back",
        },
        {
          type: "watchTower",
          x: 6500,
          y: 700,
          scale: 1.05,
          variant: 2,
          layer: "back",
        },
        {
          type: "watchTower",
          x: 8420,
          y: 700,
          scale: 1.05,
          variant: 2,
          layer: "back",
        },
        {
          type: "torch",
          x: 620,
          y: 680,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "torch",
          x: 2260,
          y: 680,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "torch",
          x: 4140,
          y: 680,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "torch",
          x: 5710,
          y: 680,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "torch",
          x: 7420,
          y: 680,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "torch",
          x: 8850,
          y: 680,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "fortressWall",
          x: 2800,
          y: 680,
          scale: 1,
          variant: 0,
          width: 1100,
          layer: "back",
        },
        {
          type: "fortressWall",
          x: 4700,
          y: 650,
          scale: 1,
          variant: 1,
          width: 1350,
          layer: "back",
        },
        {
          type: "fortressWall",
          x: 6900,
          y: 620,
          scale: 1,
          variant: 2,
          width: 1200,
          layer: "back",
        },
        {
          type: "prisonTower",
          x: 7520,
          y: 620,
          scale: 1.25,
          variant: 0,
          layer: "back",
        },
        {
          type: "harbor",
          x: 8050,
          y: 700,
          scale: 1,
          variant: 0,
          width: 1250,
        },
      ],
      enemies: [
        {
          id: "u01",
          type: "sailor",
          x: 1050,
          y: 620,
          patrol: 190,
          group: "u_a",
        },
        {
          id: "u02",
          type: "arquebusier",
          x: 1380,
          y: 440,
          patrol: 130,
          group: "u_a",
        },
        {
          id: "u03",
          type: "shield",
          x: 2180,
          y: 690,
          patrol: 170,
          group: "u_a",
        },
        {
          id: "u04",
          type: "hound",
          x: 2540,
          y: 710,
          patrol: 230,
          group: "u_a",
        },
        {
          id: "u05",
          type: "sailor",
          x: 3100,
          y: 590,
          patrol: 210,
          group: "u_b",
        },
        {
          id: "u06",
          type: "arquebusier",
          x: 3250,
          y: 410,
          patrol: 130,
          group: "u_b",
        },
        {
          id: "u07",
          type: "officer",
          x: 4060,
          y: 670,
          patrol: 180,
          group: "u_b",
        },
        {
          id: "u08",
          type: "shield",
          x: 4720,
          y: 560,
          patrol: 170,
          group: "u_c",
        },
        {
          id: "u09",
          type: "arquebusier",
          x: 5030,
          y: 360,
          patrol: 130,
          group: "u_c",
        },
        {
          id: "u10",
          type: "sailor",
          x: 5580,
          y: 570,
          patrol: 210,
          group: "u_c",
        },
        {
          id: "u11",
          type: "elite",
          x: 6280,
          y: 630,
          patrol: 190,
          group: "u_d",
          elite: true,
        },
        {
          id: "u12",
          type: "arquebusier",
          x: 7160,
          y: 330,
          patrol: 140,
          group: "u_d",
        },
        {
          id: "u13",
          type: "shield",
          x: 7840,
          y: 540,
          patrol: 180,
          group: "u_d",
        },
        {
          id: "u14",
          type: "officer",
          x: 8300,
          y: 610,
          patrol: 200,
          group: "u_e",
        },
      ],
      waterZones: [
        {
          id: "fortress_channel",
          x: 0,
          y: 690,
          w: 9300,
          h: 210,
          currentX: 8,
          currentY: 0,
        },
      ],
      powderCaches: [
        {
          id: "cache_1",
          x: 2920,
          y: 590,
          health: 130,
        },
        {
          id: "cache_2",
          x: 5180,
          y: 560,
          health: 130,
        },
        {
          id: "cache_3",
          x: 6940,
          y: 530,
          health: 150,
        },
      ],
      cages: [
        {
          id: "potira_cage",
          x: 7580,
          y: 535,
          dialogue: "potiraRescue",
          special: "potira",
        },
        {
          id: "fortress_cage_1",
          x: 4360,
          y: 670,
          dialogue: "rescuedOne",
        },
        {
          id: "fortress_cage_2",
          x: 6200,
          y: 650,
          dialogue: "rescuedTwo",
        },
      ],
      items: [
        {
          id: "arrows_u1",
          type: "arrows",
          x: 1680,
          y: 455,
          amount: 5,
        },
        {
          id: "herb_u1",
          type: "herb",
          x: 3920,
          y: 705,
          amount: 1,
        },
        {
          id: "herb_u2",
          type: "herb",
          x: 6740,
          y: 570,
          amount: 1,
        },
        {
          id: "memory_u1",
          type: "memory",
          x: 7300,
          y: 335,
          amount: 1,
        },
        {
          id: "arrows_u2",
          type: "arrows",
          x: 8080,
          y: 465,
          amount: 5,
        },
      ],
      triggers: [
        {
          id: "boss_uru",
          x: 8350,
          y: 300,
          w: 760,
          h: 520,
          action: {
            type: "startBoss",
            boss: "fortressCaptain",
            id: "boss_fortress",
          },
          once: true,
        },
      ],
      gates: [
        {
          id: "tower_gate",
          x: 7380,
          y: 380,
          w: 55,
          h: 310,
          openFlag: "caches_destroyed",
          initiallyOpen: false,
        },
      ],
      objectives: [
        {
          id: "caches",
          text: "Destrua os 3 depósitos de pólvora da fortificação.",
          condition: {
            type: "counter",
            key: "caches",
            value: 3,
          },
          onComplete: [
            {
              type: "setFlag",
              key: "caches_destroyed",
            },
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "potira",
          text: "Abra a torre e liberte Potira.",
          condition: {
            type: "flag",
            key: "rescued_potira",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "boss_uru",
          text: "Derrote o capitão que comanda Uruçumirim.",
          condition: {
            type: "flag",
            key: "boss_fortress_dead",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "harbor",
          text: "Alcance o cais antes que a armada deixe a baía.",
          condition: {
            type: "reach",
            x: 9020,
            y: 430,
            w: 240,
            h: 350,
          },
          onComplete: [
            {
              type: "completeLevel",
            },
          ],
        },
      ],
      checkpoints: [
        {
          id: "cp_uru_1",
          x: 1000,
          y: 580,
        },
        {
          id: "cp_uru_2",
          x: 3780,
          y: 620,
        },
        {
          id: "cp_uru_3",
          x: 6650,
          y: 520,
        },
      ],
      codexUnlocks: [
        "urucumirim",
        "potira-fiction",
      ],
      ambient: {
        birds: 7,
        fireflies: 0,
        leaves: 15,
        rain: 0.12,
        embers: 38,
        mist: 0.2,
        water: 0.6,
      },
    },
    navios_chamas: {
      id: "navios_chamas",
      name: "NAVIOS EM CHAMAS",
      subtitle: "A última passagem",
      palette: "ship",
      theme: "fortress",
      width: 9900,
      height: 900,
      spawn: {
        x: 200,
        y: 610,
      },
      nextLevel: null,
      introDialogue: "shipFinalEntry",
      platforms: [
        {
          x: 0,
          y: 720,
          w: 1100,
          h: 180,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 1100,
          y: 650,
          w: 1000,
          h: 250,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 2100,
          y: 760,
          w: 900,
          h: 140,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 3000,
          y: 630,
          w: 1150,
          h: 270,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 4150,
          y: 720,
          w: 950,
          h: 180,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 5100,
          y: 600,
          w: 1250,
          h: 300,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 6350,
          y: 700,
          w: 950,
          h: 200,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 7300,
          y: 560,
          w: 1450,
          h: 340,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 8750,
          y: 680,
          w: 1150,
          h: 220,
          material: "shipWood",
          oneWay: false,
        },
        {
          x: 500,
          y: 520,
          w: 420,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 1350,
          y: 450,
          w: 500,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 2300,
          y: 570,
          w: 420,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 3280,
          y: 430,
          w: 520,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 4400,
          y: 520,
          w: 440,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 5350,
          y: 390,
          w: 560,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 6570,
          y: 480,
          w: 430,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 7520,
          y: 350,
          w: 620,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
        {
          x: 8850,
          y: 490,
          w: 560,
          h: 35,
          material: "shipWood",
          oneWay: true,
        },
      ],
      decor: [
        {
          type: "mast",
          x: 200,
          y: 700,
          scale: 1.1422,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 740,
          y: 700,
          scale: 1.1098,
          variant: 2,
          layer: "back",
        },
        {
          type: "mast",
          x: 1280,
          y: 700,
          scale: 1.1768,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 1820,
          y: 700,
          scale: 1.152,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 2360,
          y: 700,
          scale: 1.025,
          variant: 3,
          layer: "back",
        },
        {
          type: "mast",
          x: 2900,
          y: 700,
          scale: 1.0326,
          variant: 0,
          layer: "back",
        },
        {
          type: "mast",
          x: 3440,
          y: 700,
          scale: 1.1013,
          variant: 3,
          layer: "back",
        },
        {
          type: "mast",
          x: 3980,
          y: 700,
          scale: 0.9219,
          variant: 2,
          layer: "back",
        },
        {
          type: "mast",
          x: 4520,
          y: 700,
          scale: 1.1352,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 5060,
          y: 700,
          scale: 1.1819,
          variant: 2,
          layer: "back",
        },
        {
          type: "mast",
          x: 5600,
          y: 700,
          scale: 0.9429,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 6140,
          y: 700,
          scale: 1.1903,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 6680,
          y: 700,
          scale: 1.124,
          variant: 0,
          layer: "back",
        },
        {
          type: "mast",
          x: 7220,
          y: 700,
          scale: 1.0195,
          variant: 3,
          layer: "back",
        },
        {
          type: "mast",
          x: 7760,
          y: 700,
          scale: 0.9488,
          variant: 1,
          layer: "back",
        },
        {
          type: "mast",
          x: 8300,
          y: 700,
          scale: 0.9484,
          variant: 3,
          layer: "back",
        },
        {
          type: "mast",
          x: 8840,
          y: 700,
          scale: 1.1982,
          variant: 3,
          layer: "back",
        },
        {
          type: "mast",
          x: 9380,
          y: 700,
          scale: 1.0017,
          variant: 1,
          layer: "back",
        },
        {
          type: "shipTorch",
          x: 720,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 1640,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 2560,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 3520,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 4480,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 5520,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 6500,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 7660,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "shipTorch",
          x: 8940,
          y: 650,
          scale: 1,
          variant: 0,
          light: true,
        },
        {
          type: "cannon",
          x: 980,
          y: 670,
          scale: 1,
          variant: 1,
        },
        {
          type: "cannon",
          x: 2850,
          y: 670,
          scale: 1,
          variant: 1,
        },
        {
          type: "cannon",
          x: 4680,
          y: 670,
          scale: 1,
          variant: 0,
        },
        {
          type: "cannon",
          x: 6760,
          y: 670,
          scale: 1,
          variant: 1,
        },
        {
          type: "cannon",
          x: 8560,
          y: 670,
          scale: 1,
          variant: 0,
        },
        {
          type: "ocean",
          x: 0,
          y: 500,
          scale: 1,
          variant: 0,
          width: 9900,
          layer: "back",
        },
        {
          type: "burningShipFar",
          x: 2100,
          y: 650,
          scale: 0.8,
          variant: 0,
          layer: "back",
        },
        {
          type: "burningShipFar",
          x: 6200,
          y: 650,
          scale: 1,
          variant: 1,
          layer: "back",
        },
        {
          type: "powderHold",
          x: 9000,
          y: 680,
          scale: 1.2,
          variant: 0,
          layer: "back",
        },
      ],
      enemies: [
        {
          id: "n01",
          type: "sailor",
          x: 860,
          y: 620,
          patrol: 200,
          group: "n_a",
        },
        {
          id: "n02",
          type: "arquebusier",
          x: 1490,
          y: 390,
          patrol: 150,
          group: "n_a",
        },
        {
          id: "n03",
          type: "shield",
          x: 1880,
          y: 560,
          patrol: 170,
          group: "n_a",
        },
        {
          id: "n04",
          type: "hound",
          x: 2580,
          y: 690,
          patrol: 230,
          group: "n_b",
        },
        {
          id: "n05",
          type: "sailor",
          x: 3220,
          y: 540,
          patrol: 210,
          group: "n_b",
        },
        {
          id: "n06",
          type: "arquebusier",
          x: 3520,
          y: 370,
          patrol: 130,
          group: "n_b",
        },
        {
          id: "n07",
          type: "officer",
          x: 4320,
          y: 620,
          patrol: 180,
          group: "n_c",
        },
        {
          id: "n08",
          type: "shield",
          x: 4820,
          y: 620,
          patrol: 180,
          group: "n_c",
        },
        {
          id: "n09",
          type: "arquebusier",
          x: 5520,
          y: 330,
          patrol: 130,
          group: "n_c",
        },
        {
          id: "n10",
          type: "elite",
          x: 6320,
          y: 600,
          patrol: 190,
          group: "n_d",
          elite: true,
        },
        {
          id: "n11",
          type: "sailor",
          x: 6920,
          y: 610,
          patrol: 210,
          group: "n_d",
        },
        {
          id: "n12",
          type: "arquebusier",
          x: 7820,
          y: 290,
          patrol: 140,
          group: "n_d",
        },
        {
          id: "n13",
          type: "shield",
          x: 8420,
          y: 590,
          patrol: 180,
          group: "n_e",
        },
        {
          id: "n14",
          type: "officer",
          x: 8950,
          y: 590,
          patrol: 200,
          group: "n_e",
        },
      ],
      items: [
        {
          id: "arrows_n1",
          type: "arrows",
          x: 1220,
          y: 405,
          amount: 5,
        },
        {
          id: "herb_n1",
          type: "herb",
          x: 4090,
          y: 665,
          amount: 1,
        },
        {
          id: "herb_n2",
          type: "herb",
          x: 7100,
          y: 650,
          amount: 1,
        },
        {
          id: "memory_n1",
          type: "memory",
          x: 8100,
          y: 300,
          amount: 1,
        },
        {
          id: "arrows_n2",
          type: "arrows",
          x: 8650,
          y: 445,
          amount: 6,
        },
      ],
      triggers: [
        {
          id: "boss_final",
          x: 7850,
          y: 250,
          w: 900,
          h: 500,
          action: {
            type: "startBoss",
            boss: "armadaCaptain",
            id: "boss_armada",
          },
          once: true,
        },
        {
          id: "final_fuse",
          x: 9200,
          y: 380,
          w: 500,
          h: 390,
          action: {
            type: "finalFuse",
          },
          once: true,
        },
      ],
      gates: [
        {
          id: "final_hold_gate",
          x: 8840,
          y: 400,
          w: 55,
          h: 300,
          openFlag: "boss_armada_dead",
          initiallyOpen: false,
        },
      ],
      objectives: [
        {
          id: "cross_fleet",
          text: "Atravesse os navios ligados por cordas e passarelas.",
          condition: {
            type: "flag",
            key: "boss_armada_started",
          },
          onComplete: [
            {
              type: "dialogue",
              id: "finalBossIntro",
            },
            {
              type: "playTheme",
              name: "boss",
            },
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "final_boss",
          text: "Derrote o Capitão-Mor da Armada.",
          condition: {
            type: "flag",
            key: "boss_armada_dead",
          },
          onComplete: [
            {
              type: "unlockObjective",
            },
          ],
        },
        {
          id: "fuse",
          text: "Alcance o porão e acenda o pavio.",
          condition: {
            type: "flag",
            key: "final_fuse_lit",
          },
          onComplete: [
            {
              type: "dialogue",
              id: "finalFuse",
            },
            {
              type: "cinematic",
              id: "final",
            },
            {
              type: "finishGame",
            },
          ],
        },
      ],
      checkpoints: [
        {
          id: "cp_ship_1",
          x: 1150,
          y: 540,
        },
        {
          id: "cp_ship_2",
          x: 4200,
          y: 600,
        },
        {
          id: "cp_ship_3",
          x: 7100,
          y: 540,
        },
      ],
      codexUnlocks: [
        "final-fiction",
        "resistance-today",
      ],
      ambient: {
        birds: 3,
        fireflies: 0,
        leaves: 0,
        rain: 0.18,
        embers: 90,
        mist: 0.2,
        water: 0.8,
      },
    },
  });

  EB.LEVEL_ORDER = Object.freeze([
    'terra_viva',
    'aldeia_chamas',
    'aguas_resistencia',
    'fogos_alianca',
    'urucumirim',
    'navios_chamas',
  ]);

  EB.getLevel = function getLevel(id) {
    const level = EB.LEVELS[id];
    return level ? EB.deepClone(level) : null;
  };
})();
